import { StyleSheet } from 'react-native';

import { colors, radius, spacing } from '@/src/theme/colors';

export const styles = StyleSheet.create({
  homeHeaderArea: {
    backgroundColor: colors.surface,
    zIndex: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text,
  },
  sectionDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  homeTop: {
    backgroundColor: colors.surface,
    paddingBottom: 8,
  },
  headerCard: {
    paddingHorizontal: spacing.md,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
  },
  locationButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  locationTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.text,
  },
  locationSubtitle: {
    fontSize: 12,
    color: colors.textMuted,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  homeSearchBar: {
    marginHorizontal: spacing.md,
    minHeight: 46,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.surfaceMuted,
  },
  homeSearchText: {
    flex: 1,
    fontSize: 14,
    color: colors.textMuted,
  },
  homeTabsWrap: {
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  feedContainer: {
    flex: 1,
  },
  feedScroll: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: spacing.md,
    paddingTop: 12,
    paddingBottom: 120,
    gap: 10,
  },
  previewBanner: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.brandSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewBannerText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
    fontWeight: '600',
  },
  homeEmptyState: {
    paddingHorizontal: 18,
    paddingVertical: 28,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    gap: 8,
  },
  homeEmptyStateTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
  },
  homeEmptyStateDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
    textAlign: 'center',
  },
  floatingButton: {
    position: 'absolute',
    right: 20,
    bottom: 26,
    minWidth: 104,
    height: 52,
    borderRadius: radius.pill,
    paddingHorizontal: 18,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brand,
    shadowColor: colors.brand,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  floatingButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#fff',
  },
  detailImage: {
    width: '100%',
    height: 260,
    backgroundColor: colors.surfaceMuted,
  },
  detailContent: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  authorName: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  metaMuted: {
    fontSize: 13,
    color: colors.textMuted,
  },
  rowWrap: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  inlineBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: radius.pill,
  },
  shareBadge: {
    backgroundColor: colors.brandSoft,
  },
  needBadge: {
    backgroundColor: colors.accentSoft,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.brand,
  },
  needBadgeText: {
    color: colors.accent,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
  },
  detailTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.text,
  },
  detailDescription: {
    fontSize: 15,
    lineHeight: 24,
    color: colors.text,
  },
  metaCard: {
    gap: 12,
    padding: 16,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metaLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  metaLineText: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
  },
  warningCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 16,
    borderRadius: radius.lg,
    backgroundColor: colors.warningSoft,
  },
  warningText: {
    flex: 1,
    color: colors.warning,
    fontWeight: '600',
  },
  bottomActions: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 22,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  notificationCard: {
    flexDirection: 'row',
    gap: 14,
    padding: 16,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
  },
  notificationUnread: {
    backgroundColor: colors.brandSoft,
  },
  notificationIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  notificationTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notificationTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  notificationTime: {
    fontSize: 12,
    color: colors.textLight,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.brand,
  },
  writeSelectContent: {
    paddingBottom: 30,
  },
  centerCard: {
    alignItems: 'center',
    gap: 10,
    padding: 22,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    marginHorizontal: spacing.lg,
  },
  centerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text,
  },
  centerDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.textMuted,
    textAlign: 'center',
  },
  writeOptionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
  },
  writeRoleNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceWarm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  writeRoleNoticeText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
    fontWeight: '600',
  },
  section: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  headerDone: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.brandSoft,
  },
  headerDoneText: {
    color: colors.brand,
    fontWeight: '700',
  },
  photoGate: {
    gap: 16,
    padding: 18,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  photoPreviewCard: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
  },
  photoPreview: {
    width: 104,
    height: 104,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
  },
  uploadPrompt: {
    alignItems: 'center',
    gap: 12,
    paddingVertical: 24,
  },
  changePhotoButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceMuted,
  },
  changePhotoText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.brand,
  },
  analysisLoading: {
    color: colors.brand,
    fontWeight: '700',
  },
  formCard: {
    gap: 16,
    padding: 18,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  aiSuggestionCard: {
    gap: 10,
    padding: 16,
    borderRadius: radius.md,
    backgroundColor: colors.brandSoft,
  },
  aiSuggestionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.brand,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  categoryRow: {
    gap: 10,
  },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  categoryChipActive: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  categoryChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textMuted,
  },
  categoryChipTextActive: {
    color: colors.brand,
  },
  locationSummaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
  },
  locationSummaryTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  locationSummarySub: {
    fontSize: 13,
    color: colors.textMuted,
  },
  errorText: {
    fontSize: 12,
    color: colors.danger,
  },
  searchBarRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  searchHeaderArea: {
    backgroundColor: colors.surface,
    zIndex: 1,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchControlsArea: {
    backgroundColor: colors.surface,
    paddingBottom: 2,
  },
  searchTabsWrap: {
    backgroundColor: colors.surface,
  },
  searchIconButton: {
    width: 50,
    height: 50,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchMeta: {
    paddingHorizontal: spacing.md,
    paddingTop: 2,
    paddingBottom: 12,
    gap: 6,
    backgroundColor: colors.surface,
  },
  searchBody: {
    flex: 1,
  },
  searchScroll: {
    flex: 1,
  },
  analysisTag: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.brand,
  },
  emptyState: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 40,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
  },
  modalDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  optionGroup: {
    gap: 10,
  },
  optionButton: {
    padding: 14,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  optionButtonActive: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  optionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textMuted,
  },
  optionLabelActive: {
    color: colors.brand,
  },
});
